name: "demo-acr"

trigger: none

parameters:
  - name: acr_name
    type: string
    default: "acrwebinardemo"
    displayName: "ACR Name"
    
  - name: location
    type: string
    default: "eastus"
    displayName: "ACR location"
    
pool: Default 

steps:
- checkout: self
      
- script:  ls  
  displayName: 'Running ACR'

- task: PowerShell@2
  displayName: "terraform init"
  inputs:
    targetType: "inline"
    script: |
     terraform init

- task: PowerShell@2
  inputs:
    targetType: "inline"
    script: |
     terraform fmt
  displayName: "terraform format" 

- task: PowerShell@2
  inputs:
    targetType: "inline"
    script: |
     terraform validate
  displayName: "validate the terraform code"

- task: PowerShell@2
  inputs:
    targetType: "inline"
    script: |
     terraform plan
  displayName: "terraform plan"
 
- task: PowerShell@2
  inputs:
    targetType: "inline"
    script: |
     terraform apply -auto-approve
  displayName: "terraform apply"



